packages:
  - "packages/*"
  - "packages/agent-integration"
  - "packages/arcana"
  - "packages/archetypal-engine"
  - "packages/art-engine-core"
  - "packages/art-generation-node"
  - "packages/art-standards-core"
  - "packages/art-systems"
  - "packages/atelier-constitution"
  - "packages/avatar-experience-system"
  - "packages/brain"
  - "packages/cataract-book-scanner"
  - "packages/cathedral-144"
  - "packages/cathedral-architect"
  - "packages/cathedral-audio-synthesis"
  - "packages/cathedral-data-core"
  - "packages/cathedral-design-library"
  - "packages/cathedral-fusion-kink-engine"
  - "packages/cathedral-integration-bridge"
  - "packages/cathedral-liber-arcanae-bridge"
  - "packages/cathedral-lightweight-library"
  - "packages/cathedral-logo-system"
  - "packages/cathedral-plugin-system"
  - "packages/cathedral-rpg-inventory-system"
  - "packages/cathedral-sqlite-persistence"
  - "packages/cathedral-style"
  - "packages/cathedral-synthesis-core"
  - "packages/cathedral-visual-engine"
  - "packages/character-alchemical-art"
  - "packages/circuit-craft-creative-game"
  - "packages/circuitum99-arcanae-cyoa"
  - "packages/circuitum99-core"
  - "packages/codex-144"
  - "packages/codex-144-99"
  - "packages/codex-144-99-core"
  - "packages/codex-144-99/data"
  - "packages/codex-engine"
  - "packages/codex-game-bridge"
  - "packages/codex-musical-system"
  - "packages/config"
  - "packages/connections"
  - "packages/consciousness-aware-creative"
  - "packages/core"
  - "packages/cosmogenesis"
  - "packages/crystals"
  - "packages/daimon-gear"
  - "packages/debug-system-core"
  - "packages/design-mathematics-core"
  - "packages/fractal-flames-daemon-deity"
  - "packages/fusion-creative-suite"
  - "packages/fusion-kink-core"
  - "packages/fusion-kink-generator"
  - "packages/fusionkink-engine"
  - "packages/game-design-core"
  - "packages/game-engine"
  - "packages/game-mathematics-core"
  - "packages/game-world"
  - "packages/gem-tower-engine"
  - "packages/godot-codex-14499"
  - "packages/godot-design-studio"
  - "packages/godot-liber-arcanae"
  - "packages/godot-vfx-library"
  - "packages/graphs"
  - "packages/hall-of-ateliers"
  - "packages/health-map-core"
  - "packages/holographic-interface"
  - "packages/inter-app-communicator"
  - "packages/kira-audio-engine"
  - "packages/labs"
  - "packages/liber-arcanae"
  - "packages/liber-arcanae-core"
  - "packages/liber-arcanae-tools"
  - "packages/living-canon-engine"
  - "packages/living-libraries"
  - "packages/luxcrux"
  - "packages/magnum-opus"
  - "packages/mobile-optimization"
  - "packages/moonchild-scanner"
  - "packages/museum-sources"
  - "packages/music-engine-core"
  - "packages/mystery-house-core"
  - "packages/mystical-data-unified"
  - "packages/mystical-sound-engine"
  - "packages/node-tree-engine"
  - "packages/physics-cannon-core"
  - "packages/portal-system"
  - "packages/professional-collaboration-engine"
  - "packages/professional-export-integration"
  - "packages/professional-quality-control"
  - "packages/professional-suite"
  - "packages/professional-typography-engine"
  - "packages/professional-vector-engine"
  - "packages/registry-learning-validation"
  - "packages/sacred-geometry-core"
  - "packages/sacred-geometry-math"
  - "packages/sacred-geometry-simd"
  - "packages/sacred-mathematics-core"
  - "packages/scanner"
  - "packages/science-engine-core"
  - "packages/shared"
  - "packages/simple-learning-validation"
  - "packages/smooth-movement-system"
  - "packages/sonic-physics-engine"
  - "packages/soul"
  - "packages/sound-mathematics-core"
  - "packages/spells"
  - "packages/spiral-learning-engine"
  - "packages/stone-grimoire"
  - "packages/stone-grimoire-core"
  - "packages/stone-grimoire-library-engine"
  - "packages/story-engine"
  - "packages/synth"
  - "packages/synth-design-math-core"
  - "packages/synth-labs"
  - "packages/synth-spells"
  - "packages/synthesis-engine"
  - "packages/tarot-art"
  - "packages/tarot-engine"
  - "packages/tarot-reader"
  - "packages/tesseract-bridge"
  - "packages/tesseract-bridge-core"
  - "packages/tesseract-bridge-hub"
  - "packages/three-engine"
  - "packages/trauma-safe-ui"
  - "packages/trinity-architecture"
  - "packages/trinity-v1-1-core"
  - "packages/types"
  - "packages/ui"
  - "packages/unified-codex-core"
  - "packages/unified-codex-extractor"
  - "packages/unified-creative-system"
  - "packages/universal-accessibility"
  - "packages/visionary-design-system"
  - "scripts/*"