name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '8'

jobs:
  # Matrix build for different Node.js versions
  test-matrix:
    name: Test Matrix (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type checking
        run: pnpm turbo run type-check

      - name: Run linting
        run: pnpm turbo run lint

      - name: Run tests
        run: pnpm turbo run test:ci
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-node-${{ matrix.node-version }}
          path: |
            **/coverage/
            **/test-results/
          retention-days: 30

  # Main CI pipeline with quality gates
  ci-build:
    name: Build & Quality Gates
    runs-on: ubuntu-latest
    needs: [test-matrix]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run build
        run: pnpm run build:ci
        env:
          CI: true
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Run quality validation
        run: pnpm run quality:full
        env:
          CI: true

      - name: Security audit
        run: pnpm run quality:security
        env:
          CI: true

      - name: Build performance validation
        run: pnpm run benchmark
        env:
          CI: true
          BENCHMARK_MODE: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/dist/
            **/lib/
            **/build/
            **/out/
          retention-days: 7

      - name: Upload quality reports
        uses: actions/upload-artifact@v4
        with:
          name: quality-reports
          path: |
            **/quality-results/
            **/security-results/
            **/benchmark-results/
          retention-days: 30

  # Build health monitoring
  build-health:
    name: Build Health Monitoring
    runs-on: ubuntu-latest
    needs: [ci-build]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install health monitoring dependencies
        run: |
          npm install -g @cathedral/build-health-monitor
          pnpm install

      - name: Run build health analysis
        run: node scripts/build-health-monitor.js
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_SHA: ${{ github.sha }}
          CI: true

      - name: Report build health
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            try {
              const healthReport = JSON.parse(fs.readFileSync('build-health-report.json', 'utf8'));
              
              const checkName = 'Build Health Status';
              const checkStatus = healthReport.status === 'healthy' ? 'success' : 'failure';
              const checkOutput = {
                title: 'Build Health Check',
                summary: `Build Status: ${healthReport.status}`,
                text: `
                  **Build Duration:** ${healthReport.buildDuration}ms
                  **Packages Built:** ${healthReport.packagesBuilt}
                  **Cache Hit Rate:** ${healthReport.cacheHitRate}%
                  **Memory Usage:** ${healthReport.memoryUsage}MB
                  **Quality Score:** ${healthReport.qualityScore}/100
                  
                  ${healthReport.recommendations.map(rec => `- ${rec}`).join('\n')}
                `
              };
              
              await github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: checkName,
                head_sha: context.sha,
                status: 'completed',
                conclusion: checkStatus,
                output: checkOutput
              });
              
            } catch (error) {
              console.log('Health report not available:', error.message);
            }

  # Deployment preparation for main branch
  deploy-staging:
    name: Prepare Staging Deployment
    runs-on: ubuntu-latest
    needs: [build-health]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create deployment manifest
        run: |
          node -e "
            const fs = require('fs');
            const manifest = {
              timestamp: new Date().toISOString(),
              commit: process.env.GITHUB_SHA,
              branch: process.env.GITHUB_REF_NAME,
              runId: process.env.GITHUB_RUN_ID,
              actor: process.env.GITHUB_ACTOR
            };
            fs.writeFileSync('deployment-manifest.json', JSON.stringify(manifest, null, 2));
          "
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Upload deployment manifest
        uses: actions/upload-artifact@v4
        with:
          name: deployment-manifest
          path: deployment-manifest.json
          retention-days: 90

  # Notification for build failures
  notify-failure:
    name: Notify Build Failure
    runs-on: ubuntu-latest
    needs: [test-matrix, ci-build, build-health]
    if: failure() && github.event_name == 'push'
    steps:
      - name: Send failure notification
        uses: actions/github-script@v7
        with:
          script: |
            const failureSummary = `
            🚨 Build Failure Alert 🚨
            
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Actor: ${{ github.actor }}
            
            Failed Jobs:
            ${{ needs.test-matrix.result === 'failure' ? '- Test Matrix' : '' }}
            ${{ needs.ci-build.result === 'failure' ? '- CI Build' : '' }}
            ${{ needs.build-health.result === 'failure' ? '- Build Health' : '' }}
            
            🔗 [View Failed Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;
            
            // Log to console for now - in production, integrate with Slack/Discord
            console.log(failureSummary);
            
            // TODO: Add webhook integration for notifications
            // Example: Slack webhook
            if (process.env.SLACK_WEBHOOK_URL) {
              // Send to Slack
            }
            
            // Example: Discord webhook  
            if (process.env.DISCORD_WEBHOOK_URL) {
              // Send to Discord
            }